spring.datasource.url=jdbc:postgresql://localhost:5432/desafioProdiga
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.web.resources.static-locations=classpath:/static/

spring.jpa.show-sql=true
spring.thymeleaf.cache=false

spring.jpa.properties.hibernate.default_schema = public
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true