spring.datasource.url=jdbc:postgresql://localhost:5432/desafioProdiga
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.web.resources.static-locations=classpath:/static/
spring.jpa.show-sql=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML